project:
  type: website
  render:
    - index.qmd
    - webpage/test/tp.qmd
    - webpage/montpellier/tp.qmd
    - webpage/toulouse/tp.qmd
    - webpage/Herault/tp.qmd
    - webpage/comparatif_grandes_villes/tp.qmd
    - webpage/Montauban/tp.qmd
    - webpage/Albi/tp.qmd
    - webpage/comparatif_moyennes_villes/tp.qmd
    - webpage/Lourdes/tp.qmd
    - webpage/La_Calmette/tp.qmd
    - webpage/comparatif_petites_villes/tp.qmd
    - webpage/HauteGaronne/tp.qmd
    - webpage/Tarn/tp.qmd
    - webpage/HautesPyrenees/tp.qmd
    - webpage/Gard/tp.qmd

website:
  back-to-top-navigation: true
  page-navigation: true # true not working in website
  title: "Projet Pollution"
  site-url: https://abelsilly.github.io/pollution/
  repo-url: https://github.com/AbelSILLY/pollution
  repo-actions: [source, issue]
  navbar:
    title: "Pollution"
    background: primary
    search: true
    left:
      - sidebar:departement
      - sidebar:villes
      - sidebar:pourallerplusloin
  sidebar:
    - id: departement
      title: "Département"
      collapse-level: 3
      contents:
        - webpage/Herault/tp.qmd
        - webpage/HauteGaronne/tp.qmd
        - webpage/Tarn/tp.qmd
        - webpage/HautesPyrenees/tp.qmd
        - webpage/Gard/tp.qmd
    - id: villes
      title: "Villes"
      collapse-level: 3
      contents:
      - webpage/montpellier/tp.qmd
      - webpage/toulouse/tp.qmd
      - webpage/comparatif_grandes_villes/tp.qmd
      - webpage/Montauban/tp.qmd
      - webpage/Albi/tp.qmd
      - webpage/comparatif_moyennes_villes/tp.qmd
      - webpage/Lourdes/tp.qmd
      - webpage/La_Calmette/tp.qmd
      - webpage/comparatif_petites_villes/tp.qmd
    - id: pourallerplusloin
      title: "Pour aller plus loin"
      collapse-level: 3
      contents:
      - webpage/test/tp.qmd


format:
  html:
    theme: cosmo
    css: styles.css
    toc: true