project:
  type: website
  render:
    - index.qmd
    - webpage/montpellier/tp.qmd

website:
  back-to-top-navigation: true
  page-navigation: true # true not working in website
  title: "Projet Pollution"
  site-url: https://abelsilly.github.io/pollution/
  repo-url: https://github.com/AbelSILLY/pollution
  navbar:
    title: "Pollution"
    background: primary
    search: true
    left:
      - sidebar:departement
      - sidebar:villes
  sidebar:
    - id: departement
      title: "Département"
      collapse-level: 3
      contents:
        - montpellier/tp.qmd
    - id: villes
      title: "Villes"
      collapse-level: 3
      contents:
      - webpage/montpellier/tp.qmd

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true