project:
  type: website
  render:
    - index.qmd
    - montpellier/tp.qmd

website:
  back-to-top-navigation: true
  page-navigation: true # true not working in website
  title: "Projet Pollution"
  site-url: https://abelsilly.github.io/pollution/
  repo-url: https://github.com/AbelSILLY/pollution

navbar:
    title: "Software dev. for data sciences"
    background: primary
    search: true
    tools:
      - icon: bicycle
        href: https://moodle.umontpellier.fr/course/view.php?id=22454
        text: Moodle
      - icon: github
        href: https://github.com/josephsalmon/HAX712X
        text: GitHub
    left:
    - sidebar:montpellier

sidebar:
    - id: montpellier
      title: "Montpellier"
      collapse-level: 3
      contents:
        - montpellier/tp.qmd

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true